spring.application.name=know-before-you-buy
spring.datasource.url=jdbc:postgresql://localhost:5432/privacy_db
spring.datasource.username=postgres
spring.datasource.password=Database

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
