spring.application.name=know-before-you-buy
spring.datasource.url=jdbc:postgresql://localhost:5432/privacy_db
spring.datasource.username=postgres
spring.datasource.password=Database

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.key=${API_KEY:api-key-123}
api.key.header=X-API-KEY

# HTTPS development config (self-signed cert, see keystore instructions)
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=Passwort
server.ssl.key-store-type=PKCS12